-- Create employees table
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  position text,
  department text,
  status text check (status in ('active', 'vacation', 'inactive')),
  avatar_url text,
  performance integer default 0,
  is_top_performer boolean default false,
  location text,
  join_date date default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.employees enable row level security;

-- Create policy to allow all actions for authenticated users (adjust as needed)
create policy "Enable all access for all users" on public.employees
  for all using (true) with check (true);
