// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: kpi.proto

package kpi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KPIMetric message
type KPIMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Target        float64                `protobuf:"fixed64,5,opt,name=target,proto3" json:"target,omitempty"`
	Current       float64                `protobuf:"fixed64,6,opt,name=current,proto3" json:"current,omitempty"`
	Percentage    float64                `protobuf:"fixed64,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KPIMetric) Reset() {
	*x = KPIMetric{}
	mi := &file_kpi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KPIMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KPIMetric) ProtoMessage() {}

func (x *KPIMetric) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KPIMetric.ProtoReflect.Descriptor instead.
func (*KPIMetric) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{0}
}

func (x *KPIMetric) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KPIMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KPIMetric) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KPIMetric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *KPIMetric) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *KPIMetric) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *KPIMetric) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// EmployeeKPI message
type EmployeeKPI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	EmployeeName  string                 `protobuf:"bytes,2,opt,name=employee_name,json=employeeName,proto3" json:"employee_name,omitempty"`
	Metrics       []*KPIMetric           `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	OverallScore  float64                `protobuf:"fixed64,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeKPI) Reset() {
	*x = EmployeeKPI{}
	mi := &file_kpi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeKPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeKPI) ProtoMessage() {}

func (x *EmployeeKPI) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeKPI.ProtoReflect.Descriptor instead.
func (*EmployeeKPI) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeKPI) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *EmployeeKPI) GetEmployeeName() string {
	if x != nil {
		return x.EmployeeName
	}
	return ""
}

func (x *EmployeeKPI) GetMetrics() []*KPIMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EmployeeKPI) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *EmployeeKPI) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *EmployeeKPI) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CalculateKPIRequest
type CalculateKPIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // monthly, weekly, daily
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateKPIRequest) Reset() {
	*x = CalculateKPIRequest{}
	mi := &file_kpi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateKPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateKPIRequest) ProtoMessage() {}

func (x *CalculateKPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateKPIRequest.ProtoReflect.Descriptor instead.
func (*CalculateKPIRequest) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateKPIRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CalculateKPIRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// CalculateKPIResponse
type CalculateKPIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpi           *EmployeeKPI           `protobuf:"bytes,1,opt,name=kpi,proto3" json:"kpi,omitempty"`
	BonusAmount   float64                `protobuf:"fixed64,2,opt,name=bonus_amount,json=bonusAmount,proto3" json:"bonus_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateKPIResponse) Reset() {
	*x = CalculateKPIResponse{}
	mi := &file_kpi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateKPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateKPIResponse) ProtoMessage() {}

func (x *CalculateKPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateKPIResponse.ProtoReflect.Descriptor instead.
func (*CalculateKPIResponse) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateKPIResponse) GetKpi() *EmployeeKPI {
	if x != nil {
		return x.Kpi
	}
	return nil
}

func (x *CalculateKPIResponse) GetBonusAmount() float64 {
	if x != nil {
		return x.BonusAmount
	}
	return 0
}

// GetKPIMetricsRequest
type GetKPIMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKPIMetricsRequest) Reset() {
	*x = GetKPIMetricsRequest{}
	mi := &file_kpi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKPIMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKPIMetricsRequest) ProtoMessage() {}

func (x *GetKPIMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKPIMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetKPIMetricsRequest) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{4}
}

func (x *GetKPIMetricsRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *GetKPIMetricsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// GetKPIMetricsResponse
type GetKPIMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpi           *EmployeeKPI           `protobuf:"bytes,1,opt,name=kpi,proto3" json:"kpi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKPIMetricsResponse) Reset() {
	*x = GetKPIMetricsResponse{}
	mi := &file_kpi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKPIMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKPIMetricsResponse) ProtoMessage() {}

func (x *GetKPIMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKPIMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetKPIMetricsResponse) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{5}
}

func (x *GetKPIMetricsResponse) GetKpi() *EmployeeKPI {
	if x != nil {
		return x.Kpi
	}
	return nil
}

// StreamKPIUpdatesRequest
type StreamKPIUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamKPIUpdatesRequest) Reset() {
	*x = StreamKPIUpdatesRequest{}
	mi := &file_kpi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamKPIUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKPIUpdatesRequest) ProtoMessage() {}

func (x *StreamKPIUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKPIUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamKPIUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{6}
}

func (x *StreamKPIUpdatesRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

// StreamKPIUpdatesResponse
type StreamKPIUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpi           *EmployeeKPI           `protobuf:"bytes,1,opt,name=kpi,proto3" json:"kpi,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamKPIUpdatesResponse) Reset() {
	*x = StreamKPIUpdatesResponse{}
	mi := &file_kpi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamKPIUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamKPIUpdatesResponse) ProtoMessage() {}

func (x *StreamKPIUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamKPIUpdatesResponse.ProtoReflect.Descriptor instead.
func (*StreamKPIUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_kpi_proto_rawDescGZIP(), []int{7}
}

func (x *StreamKPIUpdatesResponse) GetKpi() *EmployeeKPI {
	if x != nil {
		return x.Kpi
	}
	return nil
}

func (x *StreamKPIUpdatesResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_kpi_proto protoreflect.FileDescriptor

const file_kpi_proto_rawDesc = "" +
	"\n" +
	"\tkpi.proto\x12\x03kpi\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n" +
	"\tKPIMetric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x16\n" +
	"\x06target\x18\x05 \x01(\x01R\x06target\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\x01R\acurrent\x12\x1e\n" +
	"\n" +
	"percentage\x18\a \x01(\x01R\n" +
	"percentage\"\xf1\x01\n" +
	"\vEmployeeKPI\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\remployee_name\x18\x02 \x01(\tR\femployeeName\x12(\n" +
	"\ametrics\x18\x03 \x03(\v2\x0e.kpi.KPIMetricR\ametrics\x12#\n" +
	"\roverall_score\x18\x04 \x01(\x01R\foverallScore\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"N\n" +
	"\x13CalculateKPIRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"]\n" +
	"\x14CalculateKPIResponse\x12\"\n" +
	"\x03kpi\x18\x01 \x01(\v2\x10.kpi.EmployeeKPIR\x03kpi\x12!\n" +
	"\fbonus_amount\x18\x02 \x01(\x01R\vbonusAmount\"O\n" +
	"\x14GetKPIMetricsRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\";\n" +
	"\x15GetKPIMetricsResponse\x12\"\n" +
	"\x03kpi\x18\x01 \x01(\v2\x10.kpi.EmployeeKPIR\x03kpi\":\n" +
	"\x17StreamKPIUpdatesRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\"x\n" +
	"\x18StreamKPIUpdatesResponse\x12\"\n" +
	"\x03kpi\x18\x01 \x01(\v2\x10.kpi.EmployeeKPIR\x03kpi\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xec\x01\n" +
	"\n" +
	"KPIService\x12C\n" +
	"\fCalculateKPI\x12\x18.kpi.CalculateKPIRequest\x1a\x19.kpi.CalculateKPIResponse\x12F\n" +
	"\rGetKPIMetrics\x12\x19.kpi.GetKPIMetricsRequest\x1a\x1a.kpi.GetKPIMetricsResponse\x12Q\n" +
	"\x10StreamKPIUpdates\x12\x1c.kpi.StreamKPIUpdatesRequest\x1a\x1d.kpi.StreamKPIUpdatesResponse0\x01B$Z\"ai-boshqaruv-backend/api/proto/kpib\x06proto3"

var (
	file_kpi_proto_rawDescOnce sync.Once
	file_kpi_proto_rawDescData []byte
)

func file_kpi_proto_rawDescGZIP() []byte {
	file_kpi_proto_rawDescOnce.Do(func() {
		file_kpi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kpi_proto_rawDesc), len(file_kpi_proto_rawDesc)))
	})
	return file_kpi_proto_rawDescData
}

var file_kpi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kpi_proto_goTypes = []any{
	(*KPIMetric)(nil),                // 0: kpi.KPIMetric
	(*EmployeeKPI)(nil),              // 1: kpi.EmployeeKPI
	(*CalculateKPIRequest)(nil),      // 2: kpi.CalculateKPIRequest
	(*CalculateKPIResponse)(nil),     // 3: kpi.CalculateKPIResponse
	(*GetKPIMetricsRequest)(nil),     // 4: kpi.GetKPIMetricsRequest
	(*GetKPIMetricsResponse)(nil),    // 5: kpi.GetKPIMetricsResponse
	(*StreamKPIUpdatesRequest)(nil),  // 6: kpi.StreamKPIUpdatesRequest
	(*StreamKPIUpdatesResponse)(nil), // 7: kpi.StreamKPIUpdatesResponse
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_kpi_proto_depIdxs = []int32{
	0, // 0: kpi.EmployeeKPI.metrics:type_name -> kpi.KPIMetric
	8, // 1: kpi.EmployeeKPI.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: kpi.CalculateKPIResponse.kpi:type_name -> kpi.EmployeeKPI
	1, // 3: kpi.GetKPIMetricsResponse.kpi:type_name -> kpi.EmployeeKPI
	1, // 4: kpi.StreamKPIUpdatesResponse.kpi:type_name -> kpi.EmployeeKPI
	8, // 5: kpi.StreamKPIUpdatesResponse.timestamp:type_name -> google.protobuf.Timestamp
	2, // 6: kpi.KPIService.CalculateKPI:input_type -> kpi.CalculateKPIRequest
	4, // 7: kpi.KPIService.GetKPIMetrics:input_type -> kpi.GetKPIMetricsRequest
	6, // 8: kpi.KPIService.StreamKPIUpdates:input_type -> kpi.StreamKPIUpdatesRequest
	3, // 9: kpi.KPIService.CalculateKPI:output_type -> kpi.CalculateKPIResponse
	5, // 10: kpi.KPIService.GetKPIMetrics:output_type -> kpi.GetKPIMetricsResponse
	7, // 11: kpi.KPIService.StreamKPIUpdates:output_type -> kpi.StreamKPIUpdatesResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kpi_proto_init() }
func file_kpi_proto_init() {
	if File_kpi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kpi_proto_rawDesc), len(file_kpi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kpi_proto_goTypes,
		DependencyIndexes: file_kpi_proto_depIdxs,
		MessageInfos:      file_kpi_proto_msgTypes,
	}.Build()
	File_kpi_proto = out.File
	file_kpi_proto_goTypes = nil
	file_kpi_proto_depIdxs = nil
}
