// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: kpi.proto

package kpi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KPIService_CalculateKPI_FullMethodName     = "/kpi.KPIService/CalculateKPI"
	KPIService_GetKPIMetrics_FullMethodName    = "/kpi.KPIService/GetKPIMetrics"
	KPIService_StreamKPIUpdates_FullMethodName = "/kpi.KPIService/StreamKPIUpdates"
)

// KPIServiceClient is the client API for KPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KPIService
type KPIServiceClient interface {
	CalculateKPI(ctx context.Context, in *CalculateKPIRequest, opts ...grpc.CallOption) (*CalculateKPIResponse, error)
	GetKPIMetrics(ctx context.Context, in *GetKPIMetricsRequest, opts ...grpc.CallOption) (*GetKPIMetricsResponse, error)
	StreamKPIUpdates(ctx context.Context, in *StreamKPIUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamKPIUpdatesResponse], error)
}

type kPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKPIServiceClient(cc grpc.ClientConnInterface) KPIServiceClient {
	return &kPIServiceClient{cc}
}

func (c *kPIServiceClient) CalculateKPI(ctx context.Context, in *CalculateKPIRequest, opts ...grpc.CallOption) (*CalculateKPIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateKPIResponse)
	err := c.cc.Invoke(ctx, KPIService_CalculateKPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kPIServiceClient) GetKPIMetrics(ctx context.Context, in *GetKPIMetricsRequest, opts ...grpc.CallOption) (*GetKPIMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKPIMetricsResponse)
	err := c.cc.Invoke(ctx, KPIService_GetKPIMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kPIServiceClient) StreamKPIUpdates(ctx context.Context, in *StreamKPIUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamKPIUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KPIService_ServiceDesc.Streams[0], KPIService_StreamKPIUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamKPIUpdatesRequest, StreamKPIUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KPIService_StreamKPIUpdatesClient = grpc.ServerStreamingClient[StreamKPIUpdatesResponse]

// KPIServiceServer is the server API for KPIService service.
// All implementations must embed UnimplementedKPIServiceServer
// for forward compatibility.
//
// KPIService
type KPIServiceServer interface {
	CalculateKPI(context.Context, *CalculateKPIRequest) (*CalculateKPIResponse, error)
	GetKPIMetrics(context.Context, *GetKPIMetricsRequest) (*GetKPIMetricsResponse, error)
	StreamKPIUpdates(*StreamKPIUpdatesRequest, grpc.ServerStreamingServer[StreamKPIUpdatesResponse]) error
	mustEmbedUnimplementedKPIServiceServer()
}

// UnimplementedKPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKPIServiceServer struct{}

func (UnimplementedKPIServiceServer) CalculateKPI(context.Context, *CalculateKPIRequest) (*CalculateKPIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateKPI not implemented")
}
func (UnimplementedKPIServiceServer) GetKPIMetrics(context.Context, *GetKPIMetricsRequest) (*GetKPIMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKPIMetrics not implemented")
}
func (UnimplementedKPIServiceServer) StreamKPIUpdates(*StreamKPIUpdatesRequest, grpc.ServerStreamingServer[StreamKPIUpdatesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamKPIUpdates not implemented")
}
func (UnimplementedKPIServiceServer) mustEmbedUnimplementedKPIServiceServer() {}
func (UnimplementedKPIServiceServer) testEmbeddedByValue()                    {}

// UnsafeKPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KPIServiceServer will
// result in compilation errors.
type UnsafeKPIServiceServer interface {
	mustEmbedUnimplementedKPIServiceServer()
}

func RegisterKPIServiceServer(s grpc.ServiceRegistrar, srv KPIServiceServer) {
	// If the following call panics, it indicates UnimplementedKPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KPIService_ServiceDesc, srv)
}

func _KPIService_CalculateKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateKPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KPIServiceServer).CalculateKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KPIService_CalculateKPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KPIServiceServer).CalculateKPI(ctx, req.(*CalculateKPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KPIService_GetKPIMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKPIMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KPIServiceServer).GetKPIMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KPIService_GetKPIMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KPIServiceServer).GetKPIMetrics(ctx, req.(*GetKPIMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KPIService_StreamKPIUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamKPIUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KPIServiceServer).StreamKPIUpdates(m, &grpc.GenericServerStream[StreamKPIUpdatesRequest, StreamKPIUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KPIService_StreamKPIUpdatesServer = grpc.ServerStreamingServer[StreamKPIUpdatesResponse]

// KPIService_ServiceDesc is the grpc.ServiceDesc for KPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kpi.KPIService",
	HandlerType: (*KPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateKPI",
			Handler:    _KPIService_CalculateKPI_Handler,
		},
		{
			MethodName: "GetKPIMetrics",
			Handler:    _KPIService_GetKPIMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamKPIUpdates",
			Handler:       _KPIService_StreamKPIUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kpi.proto",
}
