// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: attendance.proto

package attendance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attendance message
type Attendance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId    int64                  `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CheckIn       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // present, absent, late, on_time
	MinutesLate   int32                  `protobuf:"varint,6,opt,name=minutes_late,json=minutesLate,proto3" json:"minutes_late,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendance) Reset() {
	*x = Attendance{}
	mi := &file_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendance) ProtoMessage() {}

func (x *Attendance) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendance.ProtoReflect.Descriptor instead.
func (*Attendance) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *Attendance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attendance) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *Attendance) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *Attendance) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *Attendance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Attendance) GetMinutesLate() int32 {
	if x != nil {
		return x.MinutesLate
	}
	return 0
}

func (x *Attendance) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// CheckInRequest
type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *CheckInRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CheckInRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CheckOutRequest
type CheckOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	mi := &file_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{2}
}

func (x *CheckOutRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CheckOutRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetAttendanceRequest
type GetAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceRequest) Reset() {
	*x = GetAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceRequest) ProtoMessage() {}

func (x *GetAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceRequest.ProtoReflect.Descriptor instead.
func (*GetAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{3}
}

func (x *GetAttendanceRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *GetAttendanceRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetAttendanceRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// GetAttendanceResponse
type GetAttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendances   []*Attendance          `protobuf:"bytes,1,rep,name=attendances,proto3" json:"attendances,omitempty"`
	TotalDays     int32                  `protobuf:"varint,2,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"`
	PresentDays   int32                  `protobuf:"varint,3,opt,name=present_days,json=presentDays,proto3" json:"present_days,omitempty"`
	AbsentDays    int32                  `protobuf:"varint,4,opt,name=absent_days,json=absentDays,proto3" json:"absent_days,omitempty"`
	LateDays      int32                  `protobuf:"varint,5,opt,name=late_days,json=lateDays,proto3" json:"late_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceResponse) Reset() {
	*x = GetAttendanceResponse{}
	mi := &file_attendance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceResponse) ProtoMessage() {}

func (x *GetAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceResponse.ProtoReflect.Descriptor instead.
func (*GetAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttendanceResponse) GetAttendances() []*Attendance {
	if x != nil {
		return x.Attendances
	}
	return nil
}

func (x *GetAttendanceResponse) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *GetAttendanceResponse) GetPresentDays() int32 {
	if x != nil {
		return x.PresentDays
	}
	return 0
}

func (x *GetAttendanceResponse) GetAbsentDays() int32 {
	if x != nil {
		return x.AbsentDays
	}
	return 0
}

func (x *GetAttendanceResponse) GetLateDays() int32 {
	if x != nil {
		return x.LateDays
	}
	return 0
}

var File_attendance_proto protoreflect.FileDescriptor

const file_attendance_proto_rawDesc = "" +
	"\n" +
	"\x10attendance.proto\x12\n" +
	"attendance\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x02\n" +
	"\n" +
	"Attendance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\x03R\n" +
	"employeeId\x125\n" +
	"\bcheck_in\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fminutes_late\x18\x06 \x01(\x05R\vminutesLate\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"k\n" +
	"\x0eCheckInRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"l\n" +
	"\x0fCheckOutRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa9\x01\n" +
	"\x14GetAttendanceRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xd1\x01\n" +
	"\x15GetAttendanceResponse\x128\n" +
	"\vattendances\x18\x01 \x03(\v2\x16.attendance.AttendanceR\vattendances\x12\x1d\n" +
	"\n" +
	"total_days\x18\x02 \x01(\x05R\ttotalDays\x12!\n" +
	"\fpresent_days\x18\x03 \x01(\x05R\vpresentDays\x12\x1f\n" +
	"\vabsent_days\x18\x04 \x01(\x05R\n" +
	"absentDays\x12\x1b\n" +
	"\tlate_days\x18\x05 \x01(\x05R\blateDays2\xe9\x01\n" +
	"\x11AttendanceService\x12=\n" +
	"\aCheckIn\x12\x1a.attendance.CheckInRequest\x1a\x16.attendance.Attendance\x12?\n" +
	"\bCheckOut\x12\x1b.attendance.CheckOutRequest\x1a\x16.attendance.Attendance\x12T\n" +
	"\rGetAttendance\x12 .attendance.GetAttendanceRequest\x1a!.attendance.GetAttendanceResponseB+Z)ai-boshqaruv-backend/api/proto/attendanceb\x06proto3"

var (
	file_attendance_proto_rawDescOnce sync.Once
	file_attendance_proto_rawDescData []byte
)

func file_attendance_proto_rawDescGZIP() []byte {
	file_attendance_proto_rawDescOnce.Do(func() {
		file_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)))
	})
	return file_attendance_proto_rawDescData
}

var file_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_attendance_proto_goTypes = []any{
	(*Attendance)(nil),            // 0: attendance.Attendance
	(*CheckInRequest)(nil),        // 1: attendance.CheckInRequest
	(*CheckOutRequest)(nil),       // 2: attendance.CheckOutRequest
	(*GetAttendanceRequest)(nil),  // 3: attendance.GetAttendanceRequest
	(*GetAttendanceResponse)(nil), // 4: attendance.GetAttendanceResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_attendance_proto_depIdxs = []int32{
	5,  // 0: attendance.Attendance.check_in:type_name -> google.protobuf.Timestamp
	5,  // 1: attendance.Attendance.check_out:type_name -> google.protobuf.Timestamp
	5,  // 2: attendance.Attendance.date:type_name -> google.protobuf.Timestamp
	5,  // 3: attendance.CheckInRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 4: attendance.CheckOutRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: attendance.GetAttendanceRequest.start_date:type_name -> google.protobuf.Timestamp
	5,  // 6: attendance.GetAttendanceRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 7: attendance.GetAttendanceResponse.attendances:type_name -> attendance.Attendance
	1,  // 8: attendance.AttendanceService.CheckIn:input_type -> attendance.CheckInRequest
	2,  // 9: attendance.AttendanceService.CheckOut:input_type -> attendance.CheckOutRequest
	3,  // 10: attendance.AttendanceService.GetAttendance:input_type -> attendance.GetAttendanceRequest
	0,  // 11: attendance.AttendanceService.CheckIn:output_type -> attendance.Attendance
	0,  // 12: attendance.AttendanceService.CheckOut:output_type -> attendance.Attendance
	4,  // 13: attendance.AttendanceService.GetAttendance:output_type -> attendance.GetAttendanceResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_attendance_proto_init() }
func file_attendance_proto_init() {
	if File_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attendance_proto_goTypes,
		DependencyIndexes: file_attendance_proto_depIdxs,
		MessageInfos:      file_attendance_proto_msgTypes,
	}.Build()
	File_attendance_proto = out.File
	file_attendance_proto_goTypes = nil
	file_attendance_proto_depIdxs = nil
}
