// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DailyTask message
type DailyTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionId    int64                  `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Frequency     string                 `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"` // daily, weekly, monthly, as_needed
	Priority      string                 `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`   // high, medium, low
	KpiWeight     float64                `protobuf:"fixed64,7,opt,name=kpi_weight,json=kpiWeight,proto3" json:"kpi_weight,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyTask) Reset() {
	*x = DailyTask{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTask) ProtoMessage() {}

func (x *DailyTask) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTask.ProtoReflect.Descriptor instead.
func (*DailyTask) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *DailyTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DailyTask) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *DailyTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DailyTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DailyTask) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *DailyTask) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *DailyTask) GetKpiWeight() float64 {
	if x != nil {
		return x.KpiWeight
	}
	return 0
}

func (x *DailyTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DailyTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EmployeeTask message
type EmployeeTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId    int64                  `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CompletedDate string                 `protobuf:"bytes,4,opt,name=completed_date,json=completedDate,proto3" json:"completed_date,omitempty"` // YYYY-MM-DD
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                    // pending, in_progress, completed, overdue
	QualityScore  float64                `protobuf:"fixed64,6,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeTask) Reset() {
	*x = EmployeeTask{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeTask) ProtoMessage() {}

func (x *EmployeeTask) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeTask.ProtoReflect.Descriptor instead.
func (*EmployeeTask) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeTask) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *EmployeeTask) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *EmployeeTask) GetCompletedDate() string {
	if x != nil {
		return x.CompletedDate
	}
	return ""
}

func (x *EmployeeTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmployeeTask) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *EmployeeTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EmployeeTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateTaskRequest
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    int64                  `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Frequency     string                 `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	KpiWeight     float64                `protobuf:"fixed64,6,opt,name=kpi_weight,json=kpiWeight,proto3" json:"kpi_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTaskRequest) GetKpiWeight() float64 {
	if x != nil {
		return x.KpiWeight
	}
	return 0
}

// GetTaskRequest
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListTasksRequest
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    int64                  `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"` // optional, filter by position
	Frequency     string                 `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`                      // optional, filter by frequency
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *ListTasksRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListTasksResponse
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*DailyTask           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*DailyTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTasksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// UpdateTaskRequest
type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Frequency     string                 `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	KpiWeight     float64                `protobuf:"fixed64,6,opt,name=kpi_weight,json=kpiWeight,proto3" json:"kpi_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *UpdateTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *UpdateTaskRequest) GetKpiWeight() float64 {
	if x != nil {
		return x.KpiWeight
	}
	return 0
}

// DeleteTaskRequest
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// AssignTaskRequest
type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CompletedDate string                 `protobuf:"bytes,3,opt,name=completed_date,json=completedDate,proto3" json:"completed_date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *AssignTaskRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *AssignTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *AssignTaskRequest) GetCompletedDate() string {
	if x != nil {
		return x.CompletedDate
	}
	return ""
}

// CompleteTaskRequest
type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	QualityScore  float64                `protobuf:"fixed64,3,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteTaskRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CompleteTaskRequest) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

// GetTaskMetricsRequest
type GetTaskMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // daily, weekly, monthly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskMetricsRequest) Reset() {
	*x = GetTaskMetricsRequest{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskMetricsRequest) ProtoMessage() {}

func (x *GetTaskMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskMetricsRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskMetricsRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *GetTaskMetricsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// GetTaskMetricsResponse
type GetTaskMetricsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks          int32                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	CompletedTasks      int32                  `protobuf:"varint,2,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	PendingTasks        int32                  `protobuf:"varint,3,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	OverdueTasks        int32                  `protobuf:"varint,4,opt,name=overdue_tasks,json=overdueTasks,proto3" json:"overdue_tasks,omitempty"`
	AverageQualityScore float64                `protobuf:"fixed64,5,opt,name=average_quality_score,json=averageQualityScore,proto3" json:"average_quality_score,omitempty"`
	CompletionRate      float64                `protobuf:"fixed64,6,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTaskMetricsResponse) Reset() {
	*x = GetTaskMetricsResponse{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskMetricsResponse) ProtoMessage() {}

func (x *GetTaskMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskMetricsResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskMetricsResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *GetTaskMetricsResponse) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *GetTaskMetricsResponse) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *GetTaskMetricsResponse) GetOverdueTasks() int32 {
	if x != nil {
		return x.OverdueTasks
	}
	return 0
}

func (x *GetTaskMetricsResponse) GetAverageQualityScore() float64 {
	if x != nil {
		return x.AverageQualityScore
	}
	return 0
}

func (x *GetTaskMetricsResponse) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc1\x02\n" +
	"\tDailyTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x03R\n" +
	"positionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\tR\tfrequency\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"kpi_weight\x18\a \x01(\x01R\tkpiWeight\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb2\x02\n" +
	"\fEmployeeTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\x03R\n" +
	"employeeId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12%\n" +
	"\x0ecompleted_date\x18\x04 \x01(\tR\rcompletedDate\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rquality_score\x18\x06 \x01(\x01R\fqualityScore\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc3\x01\n" +
	"\x11CreateTaskRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x03R\n" +
	"positionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\tR\tfrequency\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"kpi_weight\x18\x06 \x01(\x01R\tkpiWeight\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x82\x01\n" +
	"\x10ListTasksRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x03R\n" +
	"positionId\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\tR\tfrequency\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.task.DailyTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb2\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\tR\tfrequency\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"kpi_weight\x18\x06 \x01(\x01R\tkpiWeight\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"t\n" +
	"\x11AssignTaskRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12%\n" +
	"\x0ecompleted_date\x18\x03 \x01(\tR\rcompletedDate\"b\n" +
	"\x13CompleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rquality_score\x18\x03 \x01(\x01R\fqualityScore\"P\n" +
	"\x15GetTaskMetricsRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\x89\x02\n" +
	"\x16GetTaskMetricsResponse\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x01(\x05R\x0ecompletedTasks\x12#\n" +
	"\rpending_tasks\x18\x03 \x01(\x05R\fpendingTasks\x12#\n" +
	"\roverdue_tasks\x18\x04 \x01(\x05R\foverdueTasks\x122\n" +
	"\x15average_quality_score\x18\x05 \x01(\x01R\x13averageQualityScore\x12'\n" +
	"\x0fcompletion_rate\x18\x06 \x01(\x01R\x0ecompletionRate2\xf3\x03\n" +
	"\vTaskService\x126\n" +
	"\n" +
	"CreateTask\x12\x17.task.CreateTaskRequest\x1a\x0f.task.DailyTask\x120\n" +
	"\aGetTask\x12\x14.task.GetTaskRequest\x1a\x0f.task.DailyTask\x12<\n" +
	"\tListTasks\x12\x16.task.ListTasksRequest\x1a\x17.task.ListTasksResponse\x126\n" +
	"\n" +
	"UpdateTask\x12\x17.task.UpdateTaskRequest\x1a\x0f.task.DailyTask\x12=\n" +
	"\n" +
	"DeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\n" +
	"AssignTask\x12\x17.task.AssignTaskRequest\x1a\x12.task.EmployeeTask\x12=\n" +
	"\fCompleteTask\x12\x19.task.CompleteTaskRequest\x1a\x12.task.EmployeeTask\x12K\n" +
	"\x0eGetTaskMetrics\x12\x1b.task.GetTaskMetricsRequest\x1a\x1c.task.GetTaskMetricsResponseB%Z#ai-boshqaruv-backend/api/proto/taskb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_task_proto_goTypes = []any{
	(*DailyTask)(nil),              // 0: task.DailyTask
	(*EmployeeTask)(nil),           // 1: task.EmployeeTask
	(*CreateTaskRequest)(nil),      // 2: task.CreateTaskRequest
	(*GetTaskRequest)(nil),         // 3: task.GetTaskRequest
	(*ListTasksRequest)(nil),       // 4: task.ListTasksRequest
	(*ListTasksResponse)(nil),      // 5: task.ListTasksResponse
	(*UpdateTaskRequest)(nil),      // 6: task.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),      // 7: task.DeleteTaskRequest
	(*AssignTaskRequest)(nil),      // 8: task.AssignTaskRequest
	(*CompleteTaskRequest)(nil),    // 9: task.CompleteTaskRequest
	(*GetTaskMetricsRequest)(nil),  // 10: task.GetTaskMetricsRequest
	(*GetTaskMetricsResponse)(nil), // 11: task.GetTaskMetricsResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
}
var file_task_proto_depIdxs = []int32{
	12, // 0: task.DailyTask.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: task.DailyTask.updated_at:type_name -> google.protobuf.Timestamp
	12, // 2: task.EmployeeTask.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: task.EmployeeTask.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: task.ListTasksResponse.tasks:type_name -> task.DailyTask
	2,  // 5: task.TaskService.CreateTask:input_type -> task.CreateTaskRequest
	3,  // 6: task.TaskService.GetTask:input_type -> task.GetTaskRequest
	4,  // 7: task.TaskService.ListTasks:input_type -> task.ListTasksRequest
	6,  // 8: task.TaskService.UpdateTask:input_type -> task.UpdateTaskRequest
	7,  // 9: task.TaskService.DeleteTask:input_type -> task.DeleteTaskRequest
	8,  // 10: task.TaskService.AssignTask:input_type -> task.AssignTaskRequest
	9,  // 11: task.TaskService.CompleteTask:input_type -> task.CompleteTaskRequest
	10, // 12: task.TaskService.GetTaskMetrics:input_type -> task.GetTaskMetricsRequest
	0,  // 13: task.TaskService.CreateTask:output_type -> task.DailyTask
	0,  // 14: task.TaskService.GetTask:output_type -> task.DailyTask
	5,  // 15: task.TaskService.ListTasks:output_type -> task.ListTasksResponse
	0,  // 16: task.TaskService.UpdateTask:output_type -> task.DailyTask
	13, // 17: task.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	1,  // 18: task.TaskService.AssignTask:output_type -> task.EmployeeTask
	1,  // 19: task.TaskService.CompleteTask:output_type -> task.EmployeeTask
	11, // 20: task.TaskService.GetTaskMetrics:output_type -> task.GetTaskMetricsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
