// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: finance.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Salary message
type Salary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId      int64                  `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	BaseSalary      float64                `protobuf:"fixed64,3,opt,name=base_salary,json=baseSalary,proto3" json:"base_salary,omitempty"`
	KpiBonus        float64                `protobuf:"fixed64,4,opt,name=kpi_bonus,json=kpiBonus,proto3" json:"kpi_bonus,omitempty"`
	AttendanceBonus float64                `protobuf:"fixed64,5,opt,name=attendance_bonus,json=attendanceBonus,proto3" json:"attendance_bonus,omitempty"`
	Penalties       float64                `protobuf:"fixed64,6,opt,name=penalties,proto3" json:"penalties,omitempty"`
	Total           float64                `protobuf:"fixed64,7,opt,name=total,proto3" json:"total,omitempty"`
	Period          string                 `protobuf:"bytes,8,opt,name=period,proto3" json:"period,omitempty"` // Format: YYYY-MM
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Salary) Reset() {
	*x = Salary{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salary) ProtoMessage() {}

func (x *Salary) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salary.ProtoReflect.Descriptor instead.
func (*Salary) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Salary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Salary) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *Salary) GetBaseSalary() float64 {
	if x != nil {
		return x.BaseSalary
	}
	return 0
}

func (x *Salary) GetKpiBonus() float64 {
	if x != nil {
		return x.KpiBonus
	}
	return 0
}

func (x *Salary) GetAttendanceBonus() float64 {
	if x != nil {
		return x.AttendanceBonus
	}
	return 0
}

func (x *Salary) GetPenalties() float64 {
	if x != nil {
		return x.Penalties
	}
	return 0
}

func (x *Salary) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Salary) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Salary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Transaction message
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyId     int64                  `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // income, expense
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CalculateSalaryRequest
type CalculateSalaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // Format: YYYY-MM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSalaryRequest) Reset() {
	*x = CalculateSalaryRequest{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSalaryRequest) ProtoMessage() {}

func (x *CalculateSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSalaryRequest.ProtoReflect.Descriptor instead.
func (*CalculateSalaryRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateSalaryRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CalculateSalaryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// CalculateSalaryResponse
type CalculateSalaryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Salary           *Salary                `protobuf:"bytes,1,opt,name=salary,proto3" json:"salary,omitempty"`
	FormulaBreakdown string                 `protobuf:"bytes,2,opt,name=formula_breakdown,json=formulaBreakdown,proto3" json:"formula_breakdown,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateSalaryResponse) Reset() {
	*x = CalculateSalaryResponse{}
	mi := &file_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSalaryResponse) ProtoMessage() {}

func (x *CalculateSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSalaryResponse.ProtoReflect.Descriptor instead.
func (*CalculateSalaryResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateSalaryResponse) GetSalary() *Salary {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *CalculateSalaryResponse) GetFormulaBreakdown() string {
	if x != nil {
		return x.FormulaBreakdown
	}
	return ""
}

// GetSalaryHistoryRequest
type GetSalaryHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalaryHistoryRequest) Reset() {
	*x = GetSalaryHistoryRequest{}
	mi := &file_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalaryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalaryHistoryRequest) ProtoMessage() {}

func (x *GetSalaryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalaryHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSalaryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{4}
}

func (x *GetSalaryHistoryRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *GetSalaryHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetSalaryHistoryResponse
type GetSalaryHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salaries      []*Salary              `protobuf:"bytes,1,rep,name=salaries,proto3" json:"salaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalaryHistoryResponse) Reset() {
	*x = GetSalaryHistoryResponse{}
	mi := &file_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalaryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalaryHistoryResponse) ProtoMessage() {}

func (x *GetSalaryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalaryHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSalaryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{5}
}

func (x *GetSalaryHistoryResponse) GetSalaries() []*Salary {
	if x != nil {
		return x.Salaries
	}
	return nil
}

// GetTransactionsRequest
type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // income, expense, or empty for all
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionsRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetTransactionsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTransactionsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTransactionsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetTransactionsResponse
type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetReportsRequest
type GetReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportsRequest) Reset() {
	*x = GetReportsRequest{}
	mi := &file_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsRequest) ProtoMessage() {}

func (x *GetReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsRequest.ProtoReflect.Descriptor instead.
func (*GetReportsRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{8}
}

func (x *GetReportsRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetReportsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetReportsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// GetReportsResponse
type GetReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome   float64                `protobuf:"fixed64,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  float64                `protobuf:"fixed64,2,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	TotalSalaries float64                `protobuf:"fixed64,4,opt,name=total_salaries,json=totalSalaries,proto3" json:"total_salaries,omitempty"`
	TopExpenses   []*Transaction         `protobuf:"bytes,5,rep,name=top_expenses,json=topExpenses,proto3" json:"top_expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportsResponse) Reset() {
	*x = GetReportsResponse{}
	mi := &file_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportsResponse) ProtoMessage() {}

func (x *GetReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportsResponse.ProtoReflect.Descriptor instead.
func (*GetReportsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{9}
}

func (x *GetReportsResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *GetReportsResponse) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *GetReportsResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetReportsResponse) GetTotalSalaries() float64 {
	if x != nil {
		return x.TotalSalaries
	}
	return 0
}

func (x *GetReportsResponse) GetTopExpenses() []*Transaction {
	if x != nil {
		return x.TopExpenses
	}
	return nil
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\x06Salary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\x03R\n" +
	"employeeId\x12\x1f\n" +
	"\vbase_salary\x18\x03 \x01(\x01R\n" +
	"baseSalary\x12\x1b\n" +
	"\tkpi_bonus\x18\x04 \x01(\x01R\bkpiBonus\x12)\n" +
	"\x10attendance_bonus\x18\x05 \x01(\x01R\x0fattendanceBonus\x12\x1c\n" +
	"\tpenalties\x18\x06 \x01(\x01R\tpenalties\x12\x14\n" +
	"\x05total\x18\a \x01(\x01R\x05total\x12\x16\n" +
	"\x06period\x18\b \x01(\tR\x06period\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x03R\tcompanyId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Q\n" +
	"\x16CalculateSalaryRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"o\n" +
	"\x17CalculateSalaryResponse\x12'\n" +
	"\x06salary\x18\x01 \x01(\v2\x0f.finance.SalaryR\x06salary\x12+\n" +
	"\x11formula_breakdown\x18\x02 \x01(\tR\x10formulaBreakdown\"P\n" +
	"\x17GetSalaryHistoryRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"G\n" +
	"\x18GetSalaryHistoryResponse\x12+\n" +
	"\bsalaries\x18\x01 \x03(\v2\x0f.finance.SalaryR\bsalaries\"\xee\x01\n" +
	"\x16GetTransactionsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x9a\x01\n" +
	"\x17GetTransactionsResponse\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.finance.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa4\x01\n" +
	"\x11GetReportsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xd6\x01\n" +
	"\x12GetReportsResponse\x12!\n" +
	"\ftotal_income\x18\x01 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x02 \x01(\x01R\ftotalExpense\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12%\n" +
	"\x0etotal_salaries\x18\x04 \x01(\x01R\rtotalSalaries\x127\n" +
	"\ftop_expenses\x18\x05 \x03(\v2\x14.finance.TransactionR\vtopExpenses2\xdc\x02\n" +
	"\x0eFinanceService\x12T\n" +
	"\x0fCalculateSalary\x12\x1f.finance.CalculateSalaryRequest\x1a .finance.CalculateSalaryResponse\x12W\n" +
	"\x10GetSalaryHistory\x12 .finance.GetSalaryHistoryRequest\x1a!.finance.GetSalaryHistoryResponse\x12T\n" +
	"\x0fGetTransactions\x12\x1f.finance.GetTransactionsRequest\x1a .finance.GetTransactionsResponse\x12E\n" +
	"\n" +
	"GetReports\x12\x1a.finance.GetReportsRequest\x1a\x1b.finance.GetReportsResponseB(Z&ai-boshqaruv-backend/api/proto/financeb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_finance_proto_goTypes = []any{
	(*Salary)(nil),                   // 0: finance.Salary
	(*Transaction)(nil),              // 1: finance.Transaction
	(*CalculateSalaryRequest)(nil),   // 2: finance.CalculateSalaryRequest
	(*CalculateSalaryResponse)(nil),  // 3: finance.CalculateSalaryResponse
	(*GetSalaryHistoryRequest)(nil),  // 4: finance.GetSalaryHistoryRequest
	(*GetSalaryHistoryResponse)(nil), // 5: finance.GetSalaryHistoryResponse
	(*GetTransactionsRequest)(nil),   // 6: finance.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),  // 7: finance.GetTransactionsResponse
	(*GetReportsRequest)(nil),        // 8: finance.GetReportsRequest
	(*GetReportsResponse)(nil),       // 9: finance.GetReportsResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_finance_proto_depIdxs = []int32{
	10, // 0: finance.Salary.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: finance.Transaction.date:type_name -> google.protobuf.Timestamp
	10, // 2: finance.Transaction.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: finance.CalculateSalaryResponse.salary:type_name -> finance.Salary
	0,  // 4: finance.GetSalaryHistoryResponse.salaries:type_name -> finance.Salary
	10, // 5: finance.GetTransactionsRequest.start_date:type_name -> google.protobuf.Timestamp
	10, // 6: finance.GetTransactionsRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 7: finance.GetTransactionsResponse.transactions:type_name -> finance.Transaction
	10, // 8: finance.GetReportsRequest.start_date:type_name -> google.protobuf.Timestamp
	10, // 9: finance.GetReportsRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 10: finance.GetReportsResponse.top_expenses:type_name -> finance.Transaction
	2,  // 11: finance.FinanceService.CalculateSalary:input_type -> finance.CalculateSalaryRequest
	4,  // 12: finance.FinanceService.GetSalaryHistory:input_type -> finance.GetSalaryHistoryRequest
	6,  // 13: finance.FinanceService.GetTransactions:input_type -> finance.GetTransactionsRequest
	8,  // 14: finance.FinanceService.GetReports:input_type -> finance.GetReportsRequest
	3,  // 15: finance.FinanceService.CalculateSalary:output_type -> finance.CalculateSalaryResponse
	5,  // 16: finance.FinanceService.GetSalaryHistory:output_type -> finance.GetSalaryHistoryResponse
	7,  // 17: finance.FinanceService.GetTransactions:output_type -> finance.GetTransactionsResponse
	9,  // 18: finance.FinanceService.GetReports:output_type -> finance.GetReportsResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
