// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: contract.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contract message
type Contract struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId          int64                  `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	PositionId          int64                  `protobuf:"varint,3,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	ContractType        string                 `protobuf:"bytes,4,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"` // full_time, part_time, contractor, intern
	StartDate           string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`          // YYYY-MM-DD
	EndDate             string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                // YYYY-MM-DD (optional)
	ProbationPeriodDays int32                  `protobuf:"varint,7,opt,name=probation_period_days,json=probationPeriodDays,proto3" json:"probation_period_days,omitempty"`
	TermsJson           string                 `protobuf:"bytes,8,opt,name=terms_json,json=termsJson,proto3" json:"terms_json,omitempty"` // JSON string
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contract) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *Contract) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *Contract) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

func (x *Contract) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Contract) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Contract) GetProbationPeriodDays() int32 {
	if x != nil {
		return x.ProbationPeriodDays
	}
	return 0
}

func (x *Contract) GetTermsJson() string {
	if x != nil {
		return x.TermsJson
	}
	return ""
}

func (x *Contract) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contract) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateContractRequest
type CreateContractRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId          int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	PositionId          int64                  `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	ContractType        string                 `protobuf:"bytes,3,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
	StartDate           string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ProbationPeriodDays int32                  `protobuf:"varint,6,opt,name=probation_period_days,json=probationPeriodDays,proto3" json:"probation_period_days,omitempty"`
	TermsJson           string                 `protobuf:"bytes,7,opt,name=terms_json,json=termsJson,proto3" json:"terms_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateContractRequest) Reset() {
	*x = CreateContractRequest{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractRequest) ProtoMessage() {}

func (x *CreateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractRequest.ProtoReflect.Descriptor instead.
func (*CreateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContractRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateContractRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *CreateContractRequest) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

func (x *CreateContractRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateContractRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateContractRequest) GetProbationPeriodDays() int32 {
	if x != nil {
		return x.ProbationPeriodDays
	}
	return 0
}

func (x *CreateContractRequest) GetTermsJson() string {
	if x != nil {
		return x.TermsJson
	}
	return ""
}

// GetContractRequest
type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *GetContractRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListContractsRequest
type ListContractsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"` // optional, filter by employee
	PositionId    int64                  `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"` // optional, filter by position
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsRequest) Reset() {
	*x = ListContractsRequest{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsRequest) ProtoMessage() {}

func (x *ListContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsRequest.ProtoReflect.Descriptor instead.
func (*ListContractsRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ListContractsRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *ListContractsRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *ListContractsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContractsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListContractsResponse
type ListContractsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contracts     []*Contract            `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsResponse) Reset() {
	*x = ListContractsResponse{}
	mi := &file_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsResponse) ProtoMessage() {}

func (x *ListContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsResponse.ProtoReflect.Descriptor instead.
func (*ListContractsResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ListContractsResponse) GetContracts() []*Contract {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *ListContractsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListContractsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListContractsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// UpdateContractRequest
type UpdateContractRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractType        string                 `protobuf:"bytes,2,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`
	StartDate           string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ProbationPeriodDays int32                  `protobuf:"varint,5,opt,name=probation_period_days,json=probationPeriodDays,proto3" json:"probation_period_days,omitempty"`
	TermsJson           string                 `protobuf:"bytes,6,opt,name=terms_json,json=termsJson,proto3" json:"terms_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateContractRequest) Reset() {
	*x = UpdateContractRequest{}
	mi := &file_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractRequest) ProtoMessage() {}

func (x *UpdateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractRequest.ProtoReflect.Descriptor instead.
func (*UpdateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateContractRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContractRequest) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

func (x *UpdateContractRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateContractRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UpdateContractRequest) GetProbationPeriodDays() int32 {
	if x != nil {
		return x.ProbationPeriodDays
	}
	return 0
}

func (x *UpdateContractRequest) GetTermsJson() string {
	if x != nil {
		return x.TermsJson
	}
	return ""
}

// DeleteContractRequest
type DeleteContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContractRequest) Reset() {
	*x = DeleteContractRequest{}
	mi := &file_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContractRequest) ProtoMessage() {}

func (x *DeleteContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContractRequest.ProtoReflect.Descriptor instead.
func (*DeleteContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteContractRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\bcontract\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x84\x03\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\x03R\n" +
	"employeeId\x12\x1f\n" +
	"\vposition_id\x18\x03 \x01(\x03R\n" +
	"positionId\x12#\n" +
	"\rcontract_type\x18\x04 \x01(\tR\fcontractType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x122\n" +
	"\x15probation_period_days\x18\a \x01(\x05R\x13probationPeriodDays\x12\x1d\n" +
	"\n" +
	"terms_json\x18\b \x01(\tR\ttermsJson\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x02\n" +
	"\x15CreateContractRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x03R\n" +
	"positionId\x12#\n" +
	"\rcontract_type\x18\x03 \x01(\tR\fcontractType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x122\n" +
	"\x15probation_period_days\x18\x06 \x01(\x05R\x13probationPeriodDays\x12\x1d\n" +
	"\n" +
	"terms_json\x18\a \x01(\tR\ttermsJson\"$\n" +
	"\x12GetContractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x89\x01\n" +
	"\x14ListContractsRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x03R\n" +
	"positionId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x90\x01\n" +
	"\x15ListContractsResponse\x120\n" +
	"\tcontracts\x18\x01 \x03(\v2\x12.contract.ContractR\tcontracts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xd9\x01\n" +
	"\x15UpdateContractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rcontract_type\x18\x02 \x01(\tR\fcontractType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x122\n" +
	"\x15probation_period_days\x18\x05 \x01(\x05R\x13probationPeriodDays\x12\x1d\n" +
	"\n" +
	"terms_json\x18\x06 \x01(\tR\ttermsJson\"'\n" +
	"\x15DeleteContractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xfd\x02\n" +
	"\x0fContractService\x12E\n" +
	"\x0eCreateContract\x12\x1f.contract.CreateContractRequest\x1a\x12.contract.Contract\x12?\n" +
	"\vGetContract\x12\x1c.contract.GetContractRequest\x1a\x12.contract.Contract\x12P\n" +
	"\rListContracts\x12\x1e.contract.ListContractsRequest\x1a\x1f.contract.ListContractsResponse\x12E\n" +
	"\x0eUpdateContract\x12\x1f.contract.UpdateContractRequest\x1a\x12.contract.Contract\x12I\n" +
	"\x0eDeleteContract\x12\x1f.contract.DeleteContractRequest\x1a\x16.google.protobuf.EmptyB)Z'ai-boshqaruv-backend/api/proto/contractb\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contract_proto_goTypes = []any{
	(*Contract)(nil),              // 0: contract.Contract
	(*CreateContractRequest)(nil), // 1: contract.CreateContractRequest
	(*GetContractRequest)(nil),    // 2: contract.GetContractRequest
	(*ListContractsRequest)(nil),  // 3: contract.ListContractsRequest
	(*ListContractsResponse)(nil), // 4: contract.ListContractsResponse
	(*UpdateContractRequest)(nil), // 5: contract.UpdateContractRequest
	(*DeleteContractRequest)(nil), // 6: contract.DeleteContractRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_contract_proto_depIdxs = []int32{
	7, // 0: contract.Contract.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: contract.Contract.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: contract.ListContractsResponse.contracts:type_name -> contract.Contract
	1, // 3: contract.ContractService.CreateContract:input_type -> contract.CreateContractRequest
	2, // 4: contract.ContractService.GetContract:input_type -> contract.GetContractRequest
	3, // 5: contract.ContractService.ListContracts:input_type -> contract.ListContractsRequest
	5, // 6: contract.ContractService.UpdateContract:input_type -> contract.UpdateContractRequest
	6, // 7: contract.ContractService.DeleteContract:input_type -> contract.DeleteContractRequest
	0, // 8: contract.ContractService.CreateContract:output_type -> contract.Contract
	0, // 9: contract.ContractService.GetContract:output_type -> contract.Contract
	4, // 10: contract.ContractService.ListContracts:output_type -> contract.ListContractsResponse
	0, // 11: contract.ContractService.UpdateContract:output_type -> contract.Contract
	8, // 12: contract.ContractService.DeleteContract:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
